### PR TITLE
Wire HTTP transport settings into Credentials.

### LINKED ISSUE #49: Hadoop Connector ignores proxy settings
I have been trying to set `fs.gs.proxy.address` to no avail, for use with command line tools like `/opt/hadoop/bin/hdfs dfs -ls  gs://bucket-name`.

I checked via `tcpdump` that the connector does not try to use the proxy.

I've also tried to changed the transport type. Although setting `XXXX` does trigger an error (i.e., this is correctly taken into account), I get the same timeout backtrace with `APACHE` and `JAVA_NET`. This seems that even when transport is set to `APACHE`, the connector is attempting to use `JAVA_NET` anyway -- see following backtrace obtained with

```.xml
    <property>
        <name>fs.gs.http.transport.type</name>
        <value>APACHE</value>
    </property>
```

Finally, the connector does not log the proxy settings, so it is hard to figure out what is going on.

```
java.net.SocketTimeoutException: connect timed out
       	at java.net.PlainSocketImpl.socketConnect(Native Method)
       	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
       	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
       	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
       	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       	at java.net.Socket.connect(Socket.java:589)
       	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
       	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
       	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
       	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
       	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
       	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
       	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
       	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
       	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
       	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
       	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
       	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
       	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
       	at com.google.cloud.hadoop.util.CredentialFactory$GoogleCredentialWithRetry.executeRefreshToken(CredentialFactory.java:132)
       	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
       	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
       	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
       	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
       	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
       	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
       	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getBucket(GoogleCloudStorageImpl.java:1657)
       	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1612)
       	at com.google.cloud.hadoop.gcsio.ForwardingGoogleCloudStorage.getItemInfo(ForwardingGoogleCloudStorage.java:214)
       	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfo(GoogleCloudStorageFileSystem.java:1093)
       	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:1413)
       	at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:57)
       	at org.apache.hadoop.fs.Globber.glob(Globber.java:265)
       	at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1676)
       	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1583)
       	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1506)
       	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:326)
       	at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
       	at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
       	at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:201)
       	at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
       	at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
       	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
       	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
       	at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)
```

I am running
```
# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**edit**: I managed to make it work, through `export HADOOP_OPTS="$HADOOP_OPTS -Dhttp.proxyHost=...`. However, this is a bit confusing that the Connector's explicit configuration parameter do not seem have any effect for this.

### PR DESCRIPTION
**Pull request by pmkc**
This fixes #49 where proxy settings are not honored for authentication requests.

### CODE REVIEW

File: util/src/main/java/com/google/cloud/hadoop/util/CredentialFactory.java [hunk 1]
```diff
@@ -328,11 +341,46 @@ public Credential getStorageCredential(String clientId, String clientSecret)
...
+
+  /**
+   * @deprecated
+   * Caller should provide HttpTransport
+   */
+  @Deprecated
+  public Credential getCredentialFromFileCredentialStoreForInstalledApp(
+      String clientId, String clientSecret, String filePath, List<String> scopes)
+      throws IOException, GeneralSecurityException {
+    return getCredentialFromFileCredentialStoreForInstalledApp(
```
Comment (AngusDavis) [inline util/src/main/java/com/google/cloud/hadoop/util/CredentialFactory.java]: + getStaticTransport() arg.

Comment (pmkc) [inline util/src/main/java/com/google/cloud/hadoop/util/CredentialFactory.java]: Nice catch. Fixed

**Comment by pmkc** [comment]
PTAL
